# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Drive2Code
email: clf112358@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about Java, Spring, and being a developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chasefranks.github.io" # the base hostname & protocol for your site
github_username:  chasefranks

# other collections in addition to posts
collections:
  book_reviews:
    output: true

# enable pagination
gems: [jekyll-paginate]
paginate: 5

# Build settings
markdown: kramdown
